package com.example.gymappsas.util

const val ACTION_START_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"

const val NOTIFICATION_CHANNEL_ID = "timer_channel_id"
const val NOTIFICATION_CHANNEL_NAME = "timer_channel"
const val NOTIFICATION_ID = 143
const val ACTION_UPDATE_EXERCISE_DATA = "com.example.gymappsas.services.UPDATE_EXERCISE_DATA"
const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
const val ACTION_RESUME_SERVICE = "ACTION_RESUME_SERVICE"
const val ACTION_FORWARD_SERVICE = "ACTION_FOWARD_SERVICE"
const val ACTION_BACKWARD_SERVICE = "ACTION_BACKWARD_SERVICE"
const val ACTION_WORKOUT_FINISHED = "ACTION_WORKOUT_FINISHED"
